server:
  port: 8081
  servlet.session.tracking-modes: cookie # JESSIONID URL 전달 방식 끄기
  devtools:
    restart:
      enabled: true

logging:
  level:
    swcho.mini.mvc: debug
# HTTP요청 보기
#    org:
#      apache:
#        coyote:
#          http11: debug

spring:
  messages:
    basename: messages, errors
  # 타임리프 새로고침 없이 반영하기
  thymeleaf:
    cache: false
#    prefix: file:src/main/resources/templates/


